import { maskDocument, maskName, maskText } from "./masking.ts";
import type { IxcConnectionDto, IxcContractDto, IxcCustomerDto, IxcInvoiceDto, IxcPaymentDto, IxcPlanDto, IxcServiceOrderDto } from "./types.ts";

type Raw = Record<string,unknown>;
const str=(raw:Raw,...keys:string[])=>{for(const key of keys){const value=raw[key];if(value!==undefined&&value!==null&&String(value).trim())return String(value).trim()}return ""};
const num=(raw:Raw,...keys:string[])=>{const value=Number(str(raw,...keys).replace(",","."));return Number.isFinite(value)?value:undefined};

export class IxcCustomerMapper { static map(raw:Raw):IxcCustomerDto { const id=str(raw,"id"); if(!id)throw new Error("IXC customer sem id"); return {id,nameMasked:maskName(str(raw,"razao","nome")),documentMasked:maskDocument(str(raw,"cnpj_cpf","cpf_cnpj")),city:str(raw,"cidade","cidade_nome")||"não informada",neighborhoodMasked:maskText(str(raw,"bairro")),status:str(raw,"ativo","status")||"desconhecido",updatedAt:str(raw,"ultima_atualizacao","data")||undefined}; } }
export class IxcContractMapper { static map(raw:Raw):IxcContractDto { const id=str(raw,"id"); const customerId=str(raw,"id_cliente"); if(!id||!customerId)throw new Error("IXC contract incompleto"); return {id,customerId,planId:str(raw,"id_vd_contrato","id_produto")||undefined,planName:str(raw,"contrato","plano","descricao")||"Plano não informado",status:str(raw,"status","status_internet")||"desconhecido",dueDay:num(raw,"dia_vencimento"),monthlyValue:num(raw,"valor_plano","valor"),activatedAt:str(raw,"data_ativacao","data_inicio")||undefined}; } }
export class IxcPlanMapper { static map(raw:Raw):IxcPlanDto { const id=str(raw,"id");if(!id)throw new Error("IXC plan sem id");return{id,name:str(raw,"nome","descricao","contrato")||"Plano não informado",speed:str(raw,"velocidade","download")||undefined,value:num(raw,"valor","valor_plano")}; } }
export class IxcInvoiceMapper { static map(raw:Raw):IxcInvoiceDto { const id=str(raw,"id"); const customerId=str(raw,"id_cliente"); if(!id||!customerId)throw new Error("IXC invoice incompleta"); return {id,customerId,contractId:str(raw,"id_contrato","id_vd_contrato")||undefined,status:str(raw,"status")||"desconhecido",dueAt:str(raw,"data_vencimento","vencimento")||undefined,value:num(raw,"valor"),paymentCodeMasked:raw.linha_digitavel?maskText(raw.linha_digitavel,4):undefined}; } }
export class IxcPaymentMapper { static map(raw:Raw):IxcPaymentDto { const id=str(raw,"id"); const customerId=str(raw,"id_cliente"); if(!id||!customerId)throw new Error("IXC payment incompleto"); return {id,customerId,invoiceId:str(raw,"id_receber","id_fatura")||undefined,paidAt:str(raw,"data","data_pagamento")||undefined,value:num(raw,"valor"),method:str(raw,"tipo_recebimento","forma_pagamento")||"não informado"}; } }
export class IxcServiceOrderMapper { static map(raw:Raw):IxcServiceOrderDto { const id=str(raw,"id"); const customerId=str(raw,"id_cliente"); if(!id||!customerId)throw new Error("IXC service order incompleta"); return {id,customerId,status:str(raw,"status")||"desconhecido",subject:str(raw,"assunto","mensagem")||"Assunto mascarado",openedAt:str(raw,"data_abertura","data")||undefined,closedAt:str(raw,"data_fechamento")||undefined}; } }
export class IxcConnectionMapper { static map(raw:Raw):IxcConnectionDto { const id=str(raw,"id"); const customerId=str(raw,"id_cliente"); if(!id||!customerId)throw new Error("IXC connection incompleta"); return {id,customerId,loginMasked:maskText(str(raw,"login")),status:str(raw,"online","status")||"desconhecido",lastAccessAt:str(raw,"ultima_conexao_inicial","ultima_conexao")||undefined,addressMasked:raw.endereco?"[ENDEREÇO MASCARADO]":undefined}; } }
