import assert from "node:assert/strict";import test from "node:test";
const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("suite",`${process.pid}-${Date.now()}`);const{default:worker}=await import(workerUrl.href);const env={ASSETS:{fetch:async()=>new Response("Not found",{status:404})}};const ctx={waitUntil(){},passThroughOnException(){}};
async function turn(message,history=[]){const response=await worker.fetch(new Request("http://localhost/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,history})}),env,ctx);assert.equal(response.status,200);return response.json()}
function jaccard(a,b){const tokens=s=>new Set(s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(Boolean));const x=tokens(a),y=tokens(b),both=[...x].filter(t=>y.has(t)).length;return both/(x.size+y.size-both||1)}
test("same request rephrased advances instead of repeating",async()=>{const first=await turn("estou sem internet");const history=[{role:"customer",content:"estou sem internet"},{role:"agent",content:first.response}];const second=await turn("a conexão ainda não voltou",history);assert.ok(jaccard(first.response,second.response)<.72);assert.ok(second.evaluation.noveltyScore>.25)})
test("short yes preserves the active technical goal",async()=>{const history=[{role:"customer",content:"estou sem internet"},{role:"agent",content:"A ONU está online e o PPPoE offline. Consegue reiniciar?"}];const result=await turn("sim",history);assert.equal(result.intent,"technical_no_connection");assert.equal(result.conversationState.activeGoal,"Restaurar conexão")})
test("not working opens a protocol and never repeats reboot",async()=>{const history=[{role:"customer",content:"sem internet"},{role:"agent",content:"Desligue o roteador por 20 segundos."}];const result=await turn("não funcionou",history);assert.ok(result.tools.some(tool=>tool.tool==="support.open_ticket"));assert.ok(result.tools.some(tool=>tool.artifact?.type==="protocol"));assert.doesNotMatch(result.response,/desligar.*20 segundos/i)})
test("already rebooted is acknowledged",async()=>{const history=[{role:"customer",content:"sem internet"},{role:"agent",content:"Consegue reiniciar o roteador?"}];const result=await turn("já reiniciei",history);assert.match(result.response,/não vou pedir para reiniciar de novo/i);assert.equal(result.evaluation.unnecessaryQuestion,false)})
test("where is the PIX reuses a delivered financial goal",async()=>{const first=await turn("manda o pix da fatura");const history=[{role:"customer",content:"manda o pix da fatura"},{role:"agent",content:first.response}];const second=await turn("cadê?",history);assert.equal(second.intent,"financial_pix");assert.ok(second.tools.some(tool=>tool.artifact?.type==="pix"));assert.equal(second.evaluation.falseActionClaim,false)})
test("real intent change from support to billing is respected",async()=>{const history=[{role:"customer",content:"sem internet"},{role:"agent",content:"Estou verificando a conexão."}];const result=await turn("antes disso, manda meu boleto",history);assert.equal(result.intent,"financial_invoice");assert.ok(result.tools.some(tool=>tool.artifact?.type==="invoice"))})
test("consecutive responses expose repetition progress metrics",async()=>{const result=await turn("wifi ruim no quarto",[{role:"agent",content:"O roteador está online. O aparelho fica no mesmo cômodo?"}]);assert.equal(typeof result.evaluation.repetitionScore,"number");assert.equal(typeof result.evaluation.progressScore,"number");assert.ok(result.conversationState.fingerprints.length===1)})
test("responses ask at most one question",async()=>{for(const message of["sem internet","internet lenta","wifi ruim","preciso de ajuda"]){const result=await turn(message);assert.ok((result.response.match(/\?/g)??[]).length<=1)}})
test("handoff contains receipt and summary",async()=>{const result=await turn("quero falar com um atendente");assert.equal(result.state,"handoff");assert.ok(result.tools.some(tool=>tool.artifact?.type==="protocol"));assert.match(result.conversationSummary,/ação/)})
test("Customer 360 exposes masked data and provider sources",async()=>{const response=await worker.fetch(new Request("http://localhost/api/customers?id=DEMO-CLI-001"),env,ctx);assert.equal(response.status,200);const data=await response.json();assert.match(data.customer.maskedDocument,/\*\*\*/);assert.ok(data.sources.length>=4);assert.equal(typeof data.partial,"boolean")})
test("knowledge ingestion and evidence search work",async()=>{const title="Procedimento demo de potência óptica";const createdResponse=await worker.fetch(new Request("http://localhost/api/knowledge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"ingest",title,category:"Suporte"})}),env,ctx);assert.equal(createdResponse.status,201);const created=await createdResponse.json();await worker.fetch(new Request("http://localhost/api/knowledge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publish",id:created.id})}),env,ctx);const search=await worker.fetch(new Request("http://localhost/api/knowledge?q=potência óptica"),env,ctx);const result=await search.json();assert.ok(result.results.some(item=>item.document.title===title));assert.match(result.results[0].evidence,/Fonte interna/)})
