"use client";
import { useEffect, useState } from "react";
import type { Customer360 } from "@/lib/platform/customer360-service";
import type { CustomerSummary } from "@/lib/platform/types";

export function Customer360Module(){
  const [query,setQuery]=useState(""); const [risk,setRisk]=useState("all"); const [items,setItems]=useState<CustomerSummary[]>([]); const [selected,setSelected]=useState<Customer360|null>(null); const [state,setState]=useState<"loading"|"ready"|"error">("loading");
  useEffect(()=>{let active=true; fetch(`/api/customers?q=${encodeURIComponent(query)}&risk=${risk}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active){setItems(data.items);setState("ready")}}).catch(()=>active&&setState("error")); return()=>{active=false}},[query,risk]);
  async function open(id:string){setSelected(null); const response=await fetch(`/api/customers?id=${id}`); if(response.ok)setSelected(await response.json());else setState("error");}
  async function refresh(){if(!selected)return;const response=await fetch("/api/customers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"refresh",id:selected.customer.id})});if(response.ok)setSelected(await response.json());}
  return <main className="content"><div className="page-heading"><div><h1>Clientes e Customer 360</h1><p>Cadastro, financeiro, rede, suporte e inteligência reunidos com origem e atualização.</p></div><span className="badge green">4 fontes em paralelo</span></div>
    <section className="filter-bar"><input value={query} onChange={e=>{setState("loading");setQuery(e.target.value)}} placeholder="Buscar por nome, ID, cidade ou bairro…"/><select value={risk} onChange={e=>{setState("loading");setRisk(e.target.value)}}><option value="all">Todos os riscos</option><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="critical">Crítico</option></select></section>
    {state==="loading"&&<div className="state-card">Carregando visão unificada…</div>}{state==="error"&&<div className="state-card error">Não foi possível carregar os clientes. Tente novamente.</div>}{state==="ready"&&items.length===0&&<div className="state-card">Nenhum cliente corresponde aos filtros.</div>}
    {state==="ready"&&items.length>0&&<div className="customer360-grid"><section className="data-card"><div className="data-table"><div className="data-row header"><span>Cliente</span><span>Plano</span><span>Saúde</span><span>Risco</span><span></span></div>{items.map(c=><button className="data-row" key={c.id} onClick={()=>void open(c.id)}><span><strong>{c.name}</strong><small>{c.maskedDocument} • {c.city}</small></span><span>{c.plan}</span><span><b className={`health health-${c.health<60?"bad":c.health<80?"mid":"good"}`}>{c.health||"—"}</b></span><span><i className={`severity ${c.churnRisk}`}>{c.tags.includes("IXC somente leitura")?"controlado":c.churnRisk}</i></span><span>›</span></button>)}</div><div className="pagination"><span>1–{items.length} de {items.length}</span><button disabled>‹</button><button disabled>›</button></div></section><CustomerDetail data={selected} onRefresh={()=>void refresh()}/></div>}
  </main>;
}

function CustomerDetail({data,onRefresh}:{data:Customer360|null;onRefresh:()=>void}){if(!data)return <aside className="detail-card empty-detail"><span>◎</span><strong>Selecione um cliente</strong><p>A visão completa aparecerá aqui.</p></aside>; return <aside className="detail-card"><div className="detail-head"><div className="avatar">{data.customer.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><h3>{data.customer.name}</h3><p>{data.customer.id} • {data.customer.maskedDocument}</p></div><i className={`badge ${data.mode==="staging-readonly"?"blue":""}`}>{data.mode==="staging-readonly"?"IXC somente leitura":"Demo"}</i></div>{data.mode==="staging-readonly"&&<button className="button secondary" onClick={onRefresh}>Atualizar leitura</button>}{typeof data.totalLatencyMs==="number"&&<div className="partial-alert">Leitura total: {data.totalLatencyMs} ms • ambiente staging</div>}{data.partial&&<div className="partial-alert">Algumas fontes estão indisponíveis. Dados parciais exibidos.</div>}<DetailSection title="Contato e cadastro" rows={[["Telefone",data.contact.phone],["E-mail",data.contact.email],["Endereço",data.contact.address],["Cliente desde",data.contact.customerSince]]}/><DetailSection title="Contrato e financeiro" rows={[["Plano",data.contract.plan],["Mensalidade",`R$ ${data.contract.monthlyValue.toFixed(2).replace(".",",")}`],["Vencimento",data.contract.dueDay?`Dia ${data.contract.dueDay}`:"Indisponível"],["Em atraso",`R$ ${data.finance.overdueAmount.toFixed(2).replace(".",",")}`],["Último pagamento",data.finance.lastPayment]]}/><DetailSection title="Conexão" rows={[["Status",data.network.onuStatus],["PPPoE (login)",data.network.pppoe],["Equipamento/OLT",data.network.equipmentDescriptor],["Tipo de conexão",data.network.connectionType],["ONU",data.network.onu],["Potência",data.network.opticalPower],["Última conexão",data.network.uptime]]}/><DetailSection title="Inteligência" rows={[["Saúde",data.intelligence.health?`${data.intelligence.health}/100`:"Não calculada"],["Risco",data.intelligence.churnRisk],["Upgrade",data.intelligence.upgradeEligible?data.intelligence.recommendedPlan:"Não elegível"],["Motivo",data.intelligence.reason]]}/>{data.details&&<DetailSection title="Histórico disponível" rows={[["Contratos",String(data.details.contracts)],["Faturas",String(data.details.invoices)],["Pagamentos",String(data.details.payments)],["Ordens de serviço",String(data.details.serviceOrders)]]}/>}<div className="source-list">{data.sources.map((s,i)=><span key={i} className={s.state==="error"?"source-error":""}>● {s.provider} • {s.state==="ready"?(s.cache==="hit"?"Cache":"Homologação"):"Indisponível"} • {s.masked?"mascarado":"real"} • {s.latencyMs??0} ms</span>)}</div></aside>}
function DetailSection({title,rows}:{title:string;rows:[string,string][]}){return <div className="detail-section"><h4>{title}</h4>{rows.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
