"use client";
import { useEffect, useState } from "react";
import type { Customer360 } from "@/lib/platform/customer360-service";
import type { CustomerSummary } from "@/lib/platform/types";

export function Customer360Module(){
  const [query,setQuery]=useState(""); const [term,setTerm]=useState(""); const [risk,setRisk]=useState("all"); const [page,setPage]=useState(1); const [items,setItems]=useState<CustomerSummary[]>([]); const [total,setTotal]=useState(0); const [pageSize,setPageSize]=useState(10); const [scope,setScope]=useState<"allowlist"|"full-base">("allowlist"); const [mode,setMode]=useState<"demo"|"staging-readonly">("demo"); const [selected,setSelected]=useState<Customer360|null>(null); const [state,setState]=useState<"loading"|"ready"|"error">("loading");
  // Com a base inteira liberada, cada tecla digitada seria uma consulta ao IXC.
  // O termo só vira busca depois que a pessoa para de digitar.
  useEffect(()=>{const timer=setTimeout(()=>{setTerm(query);setPage(1)},350);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{let active=true; fetch(`/api/customers?q=${encodeURIComponent(term)}&risk=${risk}&page=${page}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active){setItems(data.items);setTotal(data.total??data.items.length);setPageSize(data.pageSize??10);setScope(data.scope??"allowlist");setMode(data.mode);setState("ready")}}).catch(()=>active&&setState("error")); return()=>{active=false}},[term,risk,page]);
  async function open(id:string){setSelected(null); const response=await fetch(`/api/customers?id=${id}`); if(response.ok)setSelected(await response.json());else setState("error");}
  async function refresh(){if(!selected)return;const response=await fetch("/api/customers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"refresh",id:selected.customer.id})});if(response.ok)setSelected(await response.json());}
  const live=mode==="staging-readonly";
  return <main className="content"><div className="page-heading"><div><h1>Clientes e Customer 360</h1><p>{live?"Cadastro real do IXC: contrato, financeiro, rede e suporte, com origem e latência de cada fonte.":"Cadastro, financeiro, rede, suporte e inteligência reunidos com origem e atualização."}</p></div><span className="badge green">{live?"7 fontes do IXC":"4 fontes em paralelo"}</span></div>
    <section className="filter-bar"><input value={query} onChange={e=>{setState("loading");setQuery(e.target.value)}} placeholder={scope==="full-base"?"Buscar por nome, CPF/CNPJ ou ID…":live?"Buscar por nome, CPF, ID ou cidade…":"Buscar por nome, ID, cidade ou bairro…"}/>{!live&&<select value={risk} onChange={e=>{setState("loading");setRisk(e.target.value)}}><option value="all">Todos os riscos</option><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="critical">Crítico</option></select>}</section>
    {live&&scope==="allowlist"&&state==="ready"&&<div className="state-card">Só os cadastros liberados na allowlist do IXC aparecem aqui. É trava nossa, de homologação — liberar a base inteira depende de <code>FEATURE_IXC_FULL_BASE</code>.</div>}
    {scope==="full-base"&&state==="ready"&&<div className="state-card">Base completa do IXC: <strong>{total.toLocaleString("pt-BR")}</strong> cadastro(s){term?" no filtro atual":""}. A busca por nome é parcial; CPF/CNPJ e ID são exatos.</div>}
    {state==="loading"&&<div className="state-card">Carregando visão unificada…</div>}{state==="error"&&<div className="state-card error">Não foi possível carregar os clientes. Tente novamente.</div>}{state==="ready"&&items.length===0&&<div className="state-card">Nenhum cliente corresponde aos filtros.</div>}
    {state==="ready"&&items.length>0&&<div className="customer360-grid"><section className="data-card"><div className="data-table"><div className="data-row header"><span>Cliente</span><span>Plano</span><span>Saúde</span><span>Risco</span><span></span></div>{items.map(c=><button className="data-row" key={c.id} onClick={()=>void open(c.id)}><span><strong>{c.name}</strong><small>{c.maskedDocument} • {c.city}</small></span><span>{c.plan}</span><span><b className={`health health-${c.health<60?"bad":c.health<80?"mid":"good"}`}>{c.health||"—"}</b></span><span><i className={`severity ${c.churnRisk}`}>{c.tags.includes("IXC somente leitura")?"controlado":c.churnRisk}</i></span><span>›</span></button>)}</div><Pagination page={page} pageSize={pageSize} total={total} shown={items.length} onChange={(next)=>{setState("loading");setPage(next)}}/></section><CustomerDetail data={selected} onRefresh={()=>void refresh()}/></div>}
  </main>;
}

function CustomerDetail({data,onRefresh}:{data:Customer360|null;onRefresh:()=>void}){if(!data)return <aside className="detail-card empty-detail"><span>◎</span><strong>Selecione um cliente</strong><p>A visão completa aparecerá aqui.</p></aside>; return <aside className="detail-card"><div className="detail-head"><div className="avatar">{data.customer.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><h3>{data.customer.name}</h3><p>{data.customer.id} • {data.customer.maskedDocument}</p></div><i className={`badge ${data.mode==="staging-readonly"?"blue":""}`}>{data.mode==="staging-readonly"?"IXC somente leitura":"Demo"}</i></div>{data.mode==="staging-readonly"&&<button className="button secondary" onClick={onRefresh}>Atualizar leitura</button>}{typeof data.totalLatencyMs==="number"&&<div className="partial-alert">Leitura total: {data.totalLatencyMs} ms • ambiente staging</div>}{data.partial&&<div className="partial-alert">Algumas fontes estão indisponíveis. Dados parciais exibidos.</div>}<DetailSection title="Contato e cadastro" rows={[["Telefone",data.contact.phone],["E-mail",data.contact.email],["Endereço",data.contact.address],["Cliente desde",data.contact.customerSince]]}/><DetailSection title="Contrato e financeiro" rows={[["Plano",data.contract.plan],["Mensalidade",`R$ ${data.contract.monthlyValue.toFixed(2).replace(".",",")}`],["Vencimento",data.contract.dueDay?`Dia ${data.contract.dueDay}`:"Indisponível"],["Em atraso",`R$ ${data.finance.overdueAmount.toFixed(2).replace(".",",")}`],["Último pagamento",data.finance.lastPayment]]}/><DetailSection title="Conexão" rows={[["Status",data.network.onuStatus],["PPPoE (login)",data.network.pppoe],["Equipamento/OLT",data.network.equipmentDescriptor],["Tipo de conexão",data.network.connectionType],["ONU",data.network.onu],["Potência",data.network.opticalPower],["Última conexão",data.network.uptime]]}/><DetailSection title="Inteligência" rows={[["Saúde",data.intelligence.health?`${data.intelligence.health}/100`:"Não calculada"],["Risco",data.intelligence.churnRisk],["Upgrade",data.intelligence.upgradeEligible?data.intelligence.recommendedPlan:"Não elegível"],["Motivo",data.intelligence.reason]]}/>{data.details&&<DetailSection title="Histórico disponível" rows={[["Contratos",String(data.details.contracts)],["Faturas",String(data.details.invoices)],["Pagamentos",String(data.details.payments)],["Ordens de serviço",String(data.details.serviceOrders)]]}/>}<div className="source-list">{data.sources.map((s,i)=><span key={i} className={s.state==="error"?"source-error":""}>● {s.provider} • {s.state==="ready"?(s.cache==="hit"?"Cache":"Homologação"):"Indisponível"} • {s.masked?"mascarado":"real"} • {s.latencyMs??0} ms</span>)}</div></aside>}
function Pagination({page,pageSize,total,shown,onChange}:{page:number;pageSize:number;total:number;shown:number;onChange:(page:number)=>void}){
  const first=total===0?0:(page-1)*pageSize+1;
  const last=(page-1)*pageSize+shown;
  const hasNext=last<total;
  return <div className="pagination"><span>{first}–{last} de {total.toLocaleString("pt-BR")}</span><button disabled={page<=1} onClick={()=>onChange(page-1)}>‹</button><button disabled={!hasNext} onClick={()=>onChange(page+1)}>›</button></div>;
}
function DetailSection({title,rows}:{title:string;rows:[string,string][]}){return <div className="detail-section"><h4>{title}</h4>{rows.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
