"use client";
import { useState } from "react";
import { leads as seedLeads } from "@/lib/platform/demo-data";
import type { Lead } from "@/lib/platform/types";
const stages=["Novo","Contato","Qualificado","Cobertura","Proposta","Documentação","Venda","Perdido"];
export function SalesModule({view}:{view:"comercial"|"leads"|"funil"|"kanban"|"metas"|"relatorios-comercial"}){const [leads,setLeads]=useState(seedLeads);if(view==="leads")return <Leads leads={leads} setLeads={setLeads}/>;if(view==="funil"||view==="kanban")return <Pipeline leads={leads} setLeads={setLeads}/>;if(view==="metas")return <Goals/>;if(view==="relatorios-comercial")return <SalesReports/>;return <SalesDashboard leads={leads}/>}
function SalesDashboard({leads}:{leads:Lead[]}){return <main className="content"><Heading title="Comercial" text="Da captação ao acompanhamento da venda, sem escrita real no IXC."/><section className="metrics"><Metric label="Leads no mês" value="614" detail="↑ 18%"/><Metric label="Qualificados" value="286" detail="46,6%"/><Metric label="Vendas demo" value="118" detail="IXC não alterado"/><Metric label="Conversão" value="19,2%" detail="Meta 18%"/></section><div className="dashboard-grid"><section className="data-card"><div className="card-header"><strong>Funil atual</strong></div>{stages.slice(0,7).map((s,i)=><div className="funnel-row" key={s}><span>{s}</span><div><i style={{width:`${100-i*11}%`}}/></div><b>{[184,152,118,96,71,49,27][i]}</b></div>)}</section><section className="data-card"><div className="card-header"><strong>Próximas ações</strong><span className="badge blue">{leads.length}</span></div>{leads.map(l=><div className="lead-compact" key={l.id}><div><strong>{l.name}</strong><span>{l.stage} • score {l.score}</span></div><small>{l.nextAction}</small></div>)}</section></div></main>}
function Leads({leads,setLeads}:{leads:Lead[];setLeads:(value:Lead[])=>void}){const [open,setOpen]=useState(false);const [saved,setSaved]=useState(false);function create(){const lead:Lead={id:`LEAD-${Date.now()}`,name:"Novo lead demonstrativo",maskedPhone:"(79) 9****-0000",city:"Itabaiana",neighborhood:"Centro",source:"WhatsApp Demo",interest:"600 Mega",coverage:"Disponível (mock)",owner:"Mariana",stage:"Novo",score:72,nextAction:"Realizar primeiro contato"};setLeads([lead,...leads]);setSaved(true);setOpen(false)}return <main className="content"><div className="page-heading"><div><h1>Leads</h1><p>Dados mascarados, cobertura mockada e histórico de próxima ação.</p></div><button className="button" onClick={()=>{setOpen(true);setSaved(false)}}>+ Novo lead</button></div>{saved&&<div className="success-banner">✓ Lead criado no LZR HUB. Nenhuma venda foi registrada no IXC.</div>}{open&&<section className="inline-form"><div><label>Nome<input defaultValue="Novo lead demonstrativo"/></label><label>Telefone mascarado<input defaultValue="(79) 9****-0000"/></label><label>Cidade<input defaultValue="Itabaiana"/></label><label>Interesse<select defaultValue="600 Mega"><option>600 Mega</option><option>400 Mega</option><option>Empresarial</option></select></label></div><p>✓ Cobertura mock disponível no Centro • consulta sem efeito externo</p><button className="button" onClick={create}>Criar lead e follow-up</button><button className="button secondary" onClick={()=>setOpen(false)}>Cancelar</button></section>}<section className="data-card"><div className="data-row sales-header"><span>Lead</span><span>Cobertura</span><span>Etapa</span><span>Score</span><span></span></div>{leads.map(l=><div className="data-row sales-header" key={l.id}><span><strong>{l.name}</strong><small>{l.maskedPhone} • {l.city}/{l.neighborhood} • {l.source}</small></span><span>{l.coverage}</span><span><i className="badge blue">{l.stage}</i></span><span><b className="health health-good">{l.score}</b></span><span>›</span></div>)}</section></main>}
function Pipeline({leads,setLeads}:{leads:Lead[];setLeads:(value:Lead[])=>void}){function move(id:string,direction:number){setLeads(leads.map(l=>{if(l.id!==id)return l;const current=Math.max(0,stages.indexOf(l.stage));return{...l,stage:stages[Math.min(stages.length-1,Math.max(0,current+direction))]}}))}return <main className="content"><Heading title="Funil e Kanban" text="Arraste conceitualmente usando as setas; cada mudança fica pronta para auditoria."/><div className="kanban">{stages.slice(0,6).map(stage=><section key={stage}><header><strong>{stage}</strong><span>{leads.filter(l=>l.stage===stage).length}</span></header>{leads.filter(l=>l.stage===stage).map(l=><article key={l.id}><strong>{l.name}</strong><p>{l.interest} • score {l.score}</p><small>{l.nextAction}</small><div><button onClick={()=>move(l.id,-1)}>‹</button><button onClick={()=>move(l.id,1)}>›</button></div></article>)}{leads.filter(l=>l.stage===stage).length===0&&<div className="kanban-empty">Nenhuma oportunidade</div>}</section>)}</div></main>}
function Goals(){return <main className="content"><Heading title="Metas comerciais" text="Acompanhamento por equipe, responsável e produto."/><section className="metrics"><Metric label="Meta de vendas" value="380" detail="Mês atual"/><Metric label="Realizado" value="241" detail="63,4%"/><Metric label="Projeção" value="396" detail="104% da meta"/><Metric label="Upgrades" value="527" detail="Meta 600"/></section><section className="data-card" style={{marginTop:14}}>{[["Equipe Itabaiana",82,120],["Equipe Regional",96,130],["Digital",63,80]].map(([name,done,goal])=><div className="goal-row" key={String(name)}><strong>{name}</strong><div className="bar"><span style={{width:`${Number(done)/Number(goal)*100}%`}}/></div><b>{done}/{goal}</b></div>)}</section></main>}
function SalesReports(){return <main className="content"><Heading title="Relatórios comerciais" text="Conversão, velocidade e origem dos leads."/><section className="metrics"><Metric label="Conversão" value="19,2%" detail="↑ 1,4 p.p."/><Metric label="Ciclo médio" value="4,2 dias" detail="↓ 0,6 dia"/><Metric label="Ticket médio" value="R$ 84,30" detail="Novas vendas"/><Metric label="Perdas" value="11,8%" detail="Principal: cobertura"/></section><section className="data-card" style={{marginTop:14}}>{[["Instagram",214,48],["Indicação",167,41],["Site",149,22],["Loja",84,18]].map(([source,total,sales])=><div className="aging-row" key={String(source)}><div><strong>{source}</strong><span>{total} leads</span></div><b>{sales} vendas demo</b></div>)}</section></main>}
function Heading({title,text}:{title:string;text:string}){return <div className="page-heading"><div><h1>{title}</h1><p>{text}</p></div><span className="badge green">Modo assistido seguro</span></div>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon">↗</span></div><strong>{value}</strong><small>{detail}</small></article>}
