"use client";
import { useState } from "react";
import { incidents } from "@/lib/platform/demo-data";
import type { NetworkIncident } from "@/lib/platform/types";

export function SupportModule({view}:{view:"monitoramento"|"mapa-alertas"|"massivas"|"chamados"}){
  if(view==="mapa-alertas")return <AlertMap/>; if(view==="massivas")return <MassIncidents/>; if(view==="chamados")return <Tickets/>; return <MonitoringCenter/>;
}
function MonitoringCenter(){return <main className="content"><Heading title="Centro de Monitoramento" text="Alertas, reclamações e eventos regionais correlacionados em tempo real." action="Atualizar fontes"/><section className="metrics"><Metric label="Alertas ativos" value="12" detail="3 críticos"/><Metric label="Clientes impactados" value="260" detail="Estimativa mock"/><Metric label="Reclamações correlatas" value="47" detail="Última hora"/><Metric label="Resolvidos hoje" value="18" detail="Tempo médio 34 min"/></section><div className="support-grid"><section className="data-card"><div className="card-header"><strong>Eventos ativos</strong><span className="badge amber">● atenção necessária</span></div>{incidents.map(i=><IncidentRow incident={i} key={i.id}/>)}</section><section className="data-card"><div className="card-header"><strong>Impacto por hora</strong><span className="badge blue">12 horas</span></div><div className="chart-bars">{[22,31,28,42,39,64,91,76,58,44,36,29].map((v,i)=><div key={i}><span style={{height:`${v}%`}}/><small>{`${i+1}h`}</small></div>)}</div><div className="event-timeline"><p><b>08:31</b> OLT-ITA-02 elevou severidade</p><p><b>08:24</b> 18 reclamações correlacionadas</p><p><b>08:12</b> Equipe técnica atribuída</p></div></section></div></main>}
function AlertMap(){return <main className="content"><Heading title="Mapa de Alertas" text="Visão geográfica operacional por cidade e bairro, sem coordenadas de clientes." action="Filtrar severidade"/><div className="map-shell"><div className="map-canvas"><div className="map-grid"/>{incidents.map((i,index)=><button key={i.id} className={`map-pin ${i.severity}`} style={{left:`${26+index*25}%`,top:`${28+index*18}%`}}><span>{i.affectedCustomers}</span><small>{i.city}</small></button>)}<div className="map-legend"><span>● Crítico</span><span>● Alto</span><span>● Médio</span></div></div><aside className="data-card"><div className="card-header"><strong>Regiões afetadas</strong></div>{incidents.map(i=><IncidentRow incident={i} key={i.id}/>)}</aside></div></main>}
function MassIncidents(){const [items,setItems]=useState(incidents);const [step,setStep]=useState(0);const flow=["Definir região","Associar equipamento","Estimar clientes","Revisar comunicação","Enfileirar demo","Acompanhar","Encerrar e auditar"];function advance(){if(step<flow.length-1)setStep(step+1);else{setItems(current=>[{id:`INC-DEMO-${Date.now()}`,title:"Massiva criada no ambiente demo",city:"Itabaiana",neighborhood:"Centro",equipment:"OLT-DEMO / PON 4",severity:"high",status:"resolved",startedAt:"agora",affectedCustomers:93,probableCause:"Simulação administrativa concluída",source:"LZR HUB Demo"},...current]);setStep(0)}}return <main className="content"><Heading title="Massivas" text="Crie, acompanhe e encerre incidentes sem comunicar clientes reais." action="Histórico de auditoria"/><div className="support-grid"><section className="data-card"><div className="card-header"><strong>Assistente de massiva demo</strong><span className="badge blue">Etapa {step+1}/{flow.length}</span></div><div className="wizard"><div className="wizard-progress"><span style={{width:`${((step+1)/flow.length)*100}%`}}/></div><h3>{flow[step]}</h3><p>{step===0?"Itabaiana • bairro Centro":step===1?"OLT-DEMO • PON 4":step===2?"93 clientes estimados":step===3?"Template informativo com opt-out":step===4?"Job demo idempotente pronto":step===5?"Entrega simulada: 0 mensagens reais":"Encerramento registrará antes/depois mascarado"}</p><button className="button" onClick={advance}>{step===flow.length-1?"Encerrar e registrar":"Confirmar etapa"}</button></div></section><section className="data-card"><div className="card-header"><strong>Massivas recentes</strong><span className="badge green">{items.length} registros</span></div>{items.map(i=><IncidentRow incident={i} key={i.id}/>)}</section></div></main>}
function Tickets(){const tickets=[["LZR-260712-1021","João Pereira","Sem conexão","Crítico","12 min"],["LZR-260712-1018","Rafael Costa","Lentidão Wi-Fi","Alto","28 min"],["LZR-260712-1004","Maria Souza","ONU offline","Normal","46 min"]];return <main className="content"><Heading title="Chamados" text="Triagem, SLA, diagnóstico e histórico técnico em uma fila única." action="Abrir chamado demo"/><section className="data-card"><div className="data-row header"><span>Protocolo / cliente</span><span>Motivo</span><span>Prioridade</span><span>SLA</span><span></span></div>{tickets.map(t=><div className="data-row" key={t[0]}><span><strong>{t[0]}</strong><small>{t[1]}</small></span><span>{t[2]}</span><span><i className={`severity ${t[3]==="Crítico"?"critical":t[3]==="Alto"?"high":"low"}`}>{t[3]}</i></span><span>{t[4]}</span><span>›</span></div>)}</section></main>}
function IncidentRow({incident:i}:{incident:NetworkIncident}){return <div className="incident-row"><i className={`severity-dot ${i.severity}`}/><div><strong>{i.title}</strong><span>{i.city} • {i.neighborhood} • {i.equipment}</span><small>{i.probableCause} • {i.source}</small></div><div><b>{i.affectedCustomers}</b><small>clientes</small><i className={`severity ${i.severity}`}>{i.severity}</i></div></div>}
function Heading({title,text,action}:{title:string;text:string;action:string}){return <div className="page-heading"><div><h1>{title}</h1><p>{text}</p></div><button className="button secondary">{action}</button></div>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon">⌁</span></div><strong>{value}</strong><small>{detail}</small></article>}
