import { getD1 } from "../../db/index";
import type { SyncRecord, SyncRepository } from "./ixc-sync";

export class D1SyncRepository implements SyncRepository {
  async create(record:SyncRecord){const db=await getD1();const duplicate=await db.prepare("SELECT id FROM sync_jobs WHERE job_type = ? AND subject_id = ? AND status = 'processing' LIMIT 1").bind("ixc-customer-refresh",record.subjectId).first();if(duplicate)return false;await db.prepare("INSERT INTO sync_jobs (id,job_type,subject_id,status,attempts,max_attempts,correlation_id,scheduled_at,created_at,updated_at) VALUES (?,?,?,?,?,2,?,?,?,?)").bind(record.id,"ixc-customer-refresh",record.subjectId,record.status,record.attempts,record.correlationId,record.at,record.at,record.at).run();return true;}
  async update(record:SyncRecord){const db=await getD1();await db.prepare("UPDATE sync_jobs SET status=?,attempts=?,error_code=?,finished_at=?,updated_at=? WHERE id=?").bind(record.status,record.attempts,record.errorCode??null,record.at,record.at,record.id).run();}
  async checkpoint(subjectId:string,status:string,correlationId:string){const now=new Date().toISOString();const db=await getD1();await db.prepare("INSERT INTO sync_checkpoints (id,provider,subject_id,last_success_at,last_attempt_at,status,correlation_id,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(provider,subject_id) DO UPDATE SET last_success_at=excluded.last_success_at,last_attempt_at=excluded.last_attempt_at,status=excluded.status,correlation_id=excluded.correlation_id,updated_at=excluded.updated_at").bind(`ixc:${subjectId}`,"ixc",subjectId,status==="completed"?now:null,now,status,correlationId,now).run();}
  async audit(subjectId:string,result:string,correlationId:string){const db=await getD1();await db.prepare("INSERT INTO audit_events (id,actor_id,role,action,entity,after_masked,reason,correlation_id,result,origin,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),"system","system","ixc.readonly.sync",`customer:${subjectId.slice(0,3)}***`,"[PAYLOAD NÃO PERSISTIDO]","Atualização controlada de homologação",correlationId,result,"human",new Date().toISOString()).run();}
}
