import { getPool } from "../../db/index";
import type { SyncRecord, SyncRepository } from "./ixc-sync";

export class D1SyncRepository implements SyncRepository {
  async create(record:SyncRecord){const pool=getPool();const duplicate=await pool.query("SELECT id FROM sync_jobs WHERE job_type = $1 AND subject_id = $2 AND status = 'processing' LIMIT 1",["ixc-customer-refresh",record.subjectId]);if(duplicate.rows[0])return false;await pool.query("INSERT INTO sync_jobs (id,job_type,subject_id,status,attempts,max_attempts,correlation_id,scheduled_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,2,$6,$7,$8,$9)",[record.id,"ixc-customer-refresh",record.subjectId,record.status,record.attempts,record.correlationId,record.at,record.at,record.at]);return true;}
  async update(record:SyncRecord){const pool=getPool();await pool.query("UPDATE sync_jobs SET status=$1,attempts=$2,error_code=$3,finished_at=$4,updated_at=$5 WHERE id=$6",[record.status,record.attempts,record.errorCode??null,record.at,record.at,record.id]);}
  async checkpoint(subjectId:string,status:string,correlationId:string){const now=new Date().toISOString();const pool=getPool();await pool.query("INSERT INTO sync_checkpoints (id,provider,subject_id,last_success_at,last_attempt_at,status,correlation_id,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(provider,subject_id) DO UPDATE SET last_success_at=excluded.last_success_at,last_attempt_at=excluded.last_attempt_at,status=excluded.status,correlation_id=excluded.correlation_id,updated_at=excluded.updated_at",[`ixc:${subjectId}`,"ixc",subjectId,status==="completed"?now:null,now,status,correlationId,now]);}
  async audit(subjectId:string,result:string,correlationId:string){const pool=getPool();await pool.query("INSERT INTO audit_events (id,actor_id,role,action,entity,after_masked,reason,correlation_id,result,origin,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[crypto.randomUUID(),"system","system","ixc.readonly.sync",`customer:${subjectId.slice(0,3)}***`,"[PAYLOAD NÃO PERSISTIDO]","Atualização controlada de homologação",correlationId,result,"human",new Date().toISOString()]);}
}
